version: '3.1'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:example@db/postgres

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example